### ISSUE TITLE
Problem with the antivirus software 

### ISSUE THREAD

**Issue by robertcb1** [DazDSP/EasyDRF#1]
Avast Free Antivirus - Prevents easydrf.exe from running then quarantines it as Win32: Malware-gen.

**Comment by DazDSP** [comment]
Some AV products appear to show a false positive to EasyDRF.

It's not clear precisely why this happens, but the most practical way to deal with it for now is to report it to the AV vendor as a false positive.

If the EasyDRF code is updated, this will probably need to be done again.

**Comment by DazDSP** [comment]
This issue has been improved since November 19, 2021 by using better compiler settings, and removing unused library code.

**Comment by DazDSP** [comment]
As of Dec 3, 2021 Avast is no longer detecting EasyDRF.exe as malware (tested using virustotal.com). Also, the file was submitted to Microsoft for analysis, and has been found to be clean - so they have removed it's detection in their products.

**Comment by DazDSP** [comment]
Each time EasyDRF is updated, it will need be be submitted to various AV vendors for analysis to prevent false-positive detections.
